# Generated by Django 3.1.7 on 2021-02-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_acc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default='', max_length=10),
        ),
    ]
