# Generated by Django 3.1.6 on 2021-02-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_acc', '0002_user_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
