# Generated by Django 3.1.6 on 2021-02-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_acc', '0003_provider_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='img/profile.png', upload_to='profile_pictures'),
        ),
    ]
