# Generated by Django 3.1.6 on 2021-02-07 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_acc', '0003_auto_20210206_2106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pysician',
            new_name='Physician',
        ),
    ]
