# Generated by Django 3.1.7 on 2021-02-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_acc', '0005_auto_20210222_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
    ]
