# Generated by Django 3.1.7 on 2021-02-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_acc', '0006_auto_20210222_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
