# Generated by Django 3.1.6 on 2021-03-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField(default=0)),
                ('water', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sleep', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mood', models.IntegerField(default=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
