# Generated by Django 3.1.6 on 2021-02-19 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_acc', '0002_auto_20210216_0334'),
        ('patient_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlog',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users_acc.patient'),
        ),
    ]
