# Generated by Django 3.1.6 on 2021-02-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlog',
            name='blood',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='patientlog',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patientlog',
            name='water',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
