# Generated by Django 3.1.6 on 2021-03-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_log', '0002_patientlog_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlog',
            name='calories',
            field=models.IntegerField(default=0, help_text='text'),
        ),
    ]
