# Generated by Django 3.1.6 on 2021-02-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_log', '0002_auto_20210207_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlog',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
