# Generated by Django 3.1.6 on 2021-03-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_log', '0003_auto_20210305_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlog',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
