# Generated by Django 3.1.6 on 2021-02-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_download', '0002_auto_20210207_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploaded_file',
            old_name='uploading_user',
            new_name='usern',
        ),
    ]
