# Generated by Django 3.1.7 on 2021-02-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_download', '0002_uploaded_file_usern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_file',
            name='file',
            field=models.FileField(upload_to='uploaded_files'),
        ),
    ]
