# Generated by Django 3.1.6 on 2021-02-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=70, null=True)),
                ('Time', models.CharField(max_length=70, null=True)),
                ('patientNum', models.PositiveIntegerField(null=True)),
                ('doctorNum', models.PositiveIntegerField(null=True)),
                ('Date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('patient', models.CharField(max_length=70, null=True)),
            ],
        ),
    ]
