# Generated by Django 3.1.6 on 2021-02-03 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApptTime', models.CharField(max_length=200)),
                ('ProviderName', models.CharField(max_length=200)),
                ('ApptDate', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='scedual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Appt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReqAppt.appt')),
            ],
        ),
    ]
