# Generated by Django 3.1.6 on 2021-02-05 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReqAppt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApptTable',
            fields=[
                ('apptId', models.AutoField(max_length=50, primary_key=True, serialize=False)),
                ('patientFname', models.CharField(max_length=40)),
                ('patientLname', models.CharField(max_length=40)),
                ('providerType', models.CharField(max_length=30)),
                ('meetingDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderTable',
            fields=[
                ('id', models.AutoField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=40)),
                ('password', models.TextField(max_length=30)),
                ('email', models.TextField(max_length=60)),
                ('firstname', models.TextField(max_length=40)),
                ('lastname', models.TextField(max_length=40)),
                ('providerType', models.TextField(max_length=30)),
                ('creationDate', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=True)),
                ('availableTimes', models.TextField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='appt',
        ),
        migrations.AddField(
            model_name='appttable',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReqAppt.providertable'),
        ),
    ]
