# Generated by Django 3.1.6 on 2021-02-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210203_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='create',
            new_name='created',
        ),
    ]
