# Generated by Django 3.1.6 on 2021-03-04 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=200)),
                ('meetingDate', models.DateTimeField(auto_now_add=True)),
                ('TheActualsender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TheActualsender', to=settings.AUTH_USER_MODEL)),
                ('Thereciever', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Thereciever', to=settings.AUTH_USER_MODEL)),
                ('Thesender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Thesender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
