# Generated by Django 3.1.6 on 2021-03-05 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogsys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postq',
            name='TheActualsender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TheActualsender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postq',
            name='Thereciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Thereciever', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postq',
            name='Thesender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Thesender', to=settings.AUTH_USER_MODEL),
        ),
    ]
