# Generated by Django 3.1.6 on 2021-03-06 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApptArchive',
            fields=[
                ('apptId', models.AutoField(primary_key=True, serialize=False)),
                ('meetingDate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=600)),
                ('apptId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptArchive.apptarchive')),
            ],
        ),
    ]
